services:
  - type: web
    name: cybersave-backend
    env: node
    region: singapore
    plan: free
    rootDir: cybersave-backend
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "mongodb+srv://sami:sami@cluster0.tmzlh9d.mongodb.net/cybersave?retryWrites=true&w=majority"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  - type: web
    name: cybersave-admin-backend
    env: node
    region: singapore
    plan: free
    rootDir: cybersave-admin-backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "mongodb+srv://sami:sami@cluster0.tmzlh9d.mongodb.net/cybersave?retryWrites=true&w=majority"
      - key: NODE_ENV
        value: production

  - type: web
    name: cybersave-admin-frontend
    env: static
    region: singapore
    plan: free
    rootDir: cybersave-admin-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: cybersave-admin-backend
          envVarKey: RENDER_EXTERNAL_URL


